# -------- ResIPy log file -------

k.showError(index=0)
k.showErrorDist(index=0)
# k.filterManual(index=0, attr="resist" # interactive plot)
k.showPseudo()
k.loadProject("/home/ben/Documents/GitHub/BenjMy/Salorno_river/GUI_proj.resipy")
k.createMesh(typ="tetra", surface=None, fmd=None, cl=-1.00, cl_factor=8.00, cln_factor=100.00, refine=0)
k.showMesh()
k.createMesh(typ="tetra", surface=None, fmd=None, cl=1.00, cl_factor=8.00, cln_factor=100.00, refine=0)
k.showMesh()
k.createMesh(typ="tetra", surface=None, fmd=None, cl=0.10, cl_factor=8.00, cln_factor=100.00, refine=0)
k.showMesh()
k.createMesh(typ="tetra", surface=None, fmd=None, cl=0.50, cl_factor=8.00, cln_factor=100.00, refine=0)
k.showMesh()
k.createMesh(typ="tetra", surface=None, fmd=None, cl=1.00, cl_factor=8.00, cln_factor=100.00, refine=0)
k.showMesh()
