# -------- ResIPy log file -------

k.showError(index=0)
k.showErrorDist(index=0)
# k.filterManual(index=0, attr="resist" # interactive plot)
k.showPseudo()
k.loadProject("/home/ben/Documents/GitHub/BenjMy/Salorno_river/GUI_prj.resipy")
# k.filterManual(index=-1, attr="reciprocalErrRel" # interactive plot)
k.showError(index=0)
k.showErrorDist(index=0)
# k.filterManual(index=0, attr="reciprocalErrRel" # interactive plot)
k.showPseudo()
k.loadProject("/home/ben/Documents/GitHub/BenjMy/Salorno_river/GUI_normalReg_TL.resipy")
# k.filterManual(index=0, attr="reciprocalErrRel" # interactive plot)
k.showErrorDist(index=0)
k.showErrorDist(index=0)
# k.filterManual(index=0, attr="reciprocalErrRel" # interactive plot)
k.showError(index=0)
k.showErrorDist(index=0)
# k.filterManual(index=0, attr="reciprocalErrRel" # interactive plot)
k.showError(index=0)
k.showErrorDist(index=0)
# k.filterManual(index=0, attr="reciprocalErrRel" # interactive plot)
k.showError(index=0)
k.showErrorDist(index=0)
# k.filterManual(index=0, attr="reciprocalErrRel" # interactive plot)
k.showError(index=0)
k.showErrorDist(index=0)
# k.filterManual(index=0, attr="reciprocalErrRel" # interactive plot)
k.showError(index=0)
k.showErrorDist(index=0)
# k.filterManual(index=0, attr="reciprocalErrRel" # interactive plot)
k.showError(index=0)
k.showErrorDist(index=0)
# k.filterManual(index=0, attr="reciprocalErrRel" # interactive plot)
k.showError(index=0)
k.showErrorDist(index=0)
# k.filterManual(index=0, attr="reciprocalErrRel" # interactive plot)
k.showError(index=0)
# k.filterManual(index=0, attr="reciprocalErrRel" # interactive plot)
k.showErrorDist(index=0)
k.showErrorDist(index=0)
# k.filterManual(index=0, attr="reciprocalErrRel" # interactive plot)
k.showError(index=0)
k.showErrorDist(index=0)
# k.filterManual(index=0, attr="reciprocalErrRel" # interactive plot)
k.showError(index=0)
k.showErrorDist(index=0)
# k.filterManual(index=0, attr="reciprocalErrRel" # interactive plot)
k.showError(index=0)
# k.filterManual(index=0, attr="reciprocalErrRel" # interactive plot)
k.showErrorDist(index=0)
# k.filterManual(index=0, attr="reciprocalErrRel" # interactive plot)
k.showErrorDist(index=0)
# k.filterManual(index=0, attr="reciprocalErrRel" # interactive plot)
k.showErrorDist(index=0)
k.showErrorDist(index=-1)
# k.filterManual(index=-1, attr="reciprocalErrRel" # interactive plot)
k.showError(index=0)
k.showErrorDist(index=-1)
# k.filterManual(index=-1, attr="reciprocalErrRel" # interactive plot)
k.showError(index=0)
k.showErrorDist(index=-1)
# k.filterManual(index=-1, attr="reciprocalErrRel" # interactive plot)
k.showError(index=0)
k.showErrorDist(index=-1)
# k.filterManual(index=-1, attr="reciprocalErrRel" # interactive plot)
k.showError(index=0)
k.showErrorDist(index=-1)
# k.filterManual(index=-1, attr="reciprocalErrRel" # interactive plot)
k.showError(index=0)
k.showErrorDist(index=-1)
# k.filterManual(index=-1, attr="reciprocalErrRel" # interactive plot)
k.showError(index=0)
# k.filterManual(index=-1, attr="app" # interactive plot)
k.filterAppResist(index=-1, vmin=0.0, vmax=1000.0)
k.showErrorDist(index=-1)
# k.filterManual(index=-1, attr="app" # interactive plot)
k.showError(index=0)
